---
title: "Wykrywanie farm fotowoltaicznych na&nbsp;podstawie danych teledetekcyjnych"
description: |
  Konspekt pracy inżynierskiej
author:
  - name: Filip Ratajszczak
    url: https://www.linkedin.com/in/filip-ratajszczak/
    affiliation: Wydział Nauk Geograficznych i Geologicznych
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
---

```{=html}
<style>
    p {
    text-align: justify
    }
</style>
```
```{r include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, layout="l-body-outset")
```

<p>

## Wstęp

Następujące zmiany klimatyczne oraz kryzys energetyczny związany z wybuchem wojny na Ukrainie wymuszają na społeczeństwie odejście od produkcji energii z paliw kopalnych na rzecz odnawialnych źródeł energii i energetyki jądrowej. Transformacja energetyczna jest procesem bardzo dynamicznym, którego monitorowanie ma istotny wpływ na rozwój kolejnych projektów dotyczących energetyki niekonwencjonalnej. Niejednolita organizacja działania władz samorządowych w Polsce oraz występowanie na terenie kraju różnych operatorów energetycznych uniemożliwia śledzenie rozwoju branży OZE w Polsce.

W Bazie Danych Obiektów Topograficznych ([BDOT 10k](https://www.geoportal.gov.pl/dane/baza-danych-obiektow-topograficznych-bdot)) zawarte są dane na temat lokalizacji turbin wiatrowych w Polsce. W oficjalnych, dostępnych w Polsce danych brakuje jednak informacji na temat lokalizacji elektrowni fotowoltaicznych. Wśród nieoficjalnych źródeł danych informacje na ten temat można znaleźć m.in. w projekcie społeczności internetowej [OpenStreetMap](https://www.openstreetmap.org/) pod tagiem ["solar"](https://wiki.openstreetmap.org/wiki/Tag:generator:source%3Dsolar), jednak dane te są nieformalne, niepełne i nieaktualne.

Wykorzystanie metod uczenia maszynowego i uczenia głębokiego pozwala na wykrywanie różnego typu zmian masowych zachodzących na dużych powierzchniach, nawet na powierzchni całej Ziemi. Rozwijające się systemy obserwacji planety dostarczają coraz więcej danych, stale skracane są czasy rewizyt oraz zwiększana jest rozdzielczość przestrzenna w nowych, kolejnych misjach czy programach. Dane zostają również coraz częściej uwalniane - udostępniane są do pobierania za darmo, w przyjazny dla użytkownika sposób - za pomocą portali internetowych takich jak np. [CREODIAS](https://creodias.eu/), bez potrzeby pisania wniosków o dostęp do informacji.

Celem zamierzonej pracy inżynierskiej jest wykrywanie farm fotowoltaicznych na podstawie danych teledetekcyjnych jednego lub dwóch pułapów (pułapu satelitarnego lub pułapu satelitarnego i lotniczego). Praca zakłada wykorzystanie do tego celu technologii uczenia maszynowego (*ang. machine learning)* i/lub uczenia głębokiego (*ang. deep learning)* w postaci sieci neuronowych (*ang. neural networks*).

### Możliwe problemy:

-   różne układy współrzędnych wykorzystywanych danych (ortofotomapa - [ETRF2000-PL / CS92](https://epsg.io/2180); Sentinel-2, PlanetScope - [WGS 84 / UTM zone 33N](https://epsg.io/32633); Google Satellite, Planet Basemaps, Bing Aerial, Mapbox Satellite itp. - [Web Mercator](https://epsg.io/3857))

-   misja Sentinel-2 oferuje 4 kanały w rozdzielczości 10 m oraz 6 kanałów w rozdzielczości 20 m - możliwe, że konieczne będzie wykorzystanie kanałów o rozdzielczości 20 m oraz downsampling kanałów o rozdzielczości 10 m do 20 m

    -alternatywnie wykorzystanie danych przeprocesowanych algorytmem [sen2res](https://step.esa.int/main/snap-supported-plugins/sen2res/) dostępnym w oprogramowaniu [SNAP](https://step.esa.int/main/toolboxes/snap/) (upsampling wszystkich kanałów do 10 m)

-   brak aktualnych ortofotomap

-   podobna barwa farm fotowoltaicznych do innych obiektów antropogenicznych (np. szklarnie, zabudowa przemysłowa, parkingi itp.) lub czasami nawet gołe pola (przynajmniej na kompozycji RGB na podstawie danych Sentinel-2)

-   różne typy pokrycia powierzchni pomiędzy modułami fotowoltaicznymi (trawa, goła gleba itp.), co może wpływać na wartości odbicia spektralnego

-   potrzeba dużej mocy obliczeniowej przy wykorzystaniu uczenia głębokiego (sieci neuronowych)

## Cel pracy

Celem pracy jest stworzenie algorytmu umożliwiającego wykrywanie farm fotowoltaicznych na podstawie danych teledetekcyjnych w skali regionu lub kraju, którego efektami będą przestrzenne dane wektorowe lub rastrowe.

Zlokalizowane farmy (jako dane przestrzenne) mogą być wykorzystane w wielu celach, np.:

-   prowadzenie statystki energii odnawialnej w Polsce

-   inwentaryzacja ilościowa i powierzchniowa farm fotowoltaicznych na różnych szczeblach podziału administracyjnego (gminnym, powiatowym, wojewódzkim, krajowym)

-   szacowanie ilości energii jaką aktualnie takie instalacje wytwarzają na terenie danych jednostek podziału administracyjnego

-   monitorowanie zachodzących zmian w wybranych interwałach czasowych (np. co rok) - uruchamianie algorytmu w regularnych odstępach czasu na podstawie najnowszych dostępnych danych

## Przewidywane etapy pracy

1.  Stworzenie zbioru danych testowych i treningowych na obszarze kafla 33UWV ze zbioru danych Sentinel-2 na podstawie usług sieciowych (WMS, WMTS, XYZ Tiles): ortofotomapy, Google Satellite, Bing Aerial, Mapbox Satellite, Planet Basemaps

2.  Stworzenie algorytmu uczenia maszynowego do wstępnego wykrywania farm fotowoltaicznych na obszarze kafla 33UWV ze zbioru danych Sentinel-2 (wykorzystywane dane: Sentinel-2 Level-2A, rozdzielczość 10 lub 20 m)

3.  Zależnie od czasu, w jakim zostanie zakończony etap drugi oraz jego wyników, możliwe są dwie ścieżki rozwoju pracy:

    3a. pobranie ortofotomapy (rozdzielczość 25 cm) dla obszarów wstępnie wytypowanych w etapie 2. za pomocą pakietu [rgugik](https://kadyb.github.io/rgugik/) (Dyba, Nowosad 2021); stworzenie algorytmu uczenia głębokiego do wykrywania dokładnych granic farm fotowoltaicznych

    3b. pobranie danych satelitarnych z programu PlanetScope (rozdzielczość 3 m) dla obszarów wstępnie wytypowanych w etapie 2. za pomocą [Planet API](https://developers.planet.com/docs/apis/), stworzenie algorytmu uczenia maszynowego do wykrywania dokładnych granic farm fotowoltaicznych

4.  Wykorzystanie stworzonych algorytmów na większym obszarze, np. kilku kafli Sentinel-2 lub obszaru całej Polski

5.  Stworzenie produktów końcowych - danych przestrzennych reprezentujących farmy fotowoltaiczne

## Planowane efekty pracy

Planowanymi efektami pracy są:

-   algorytm(y) umożliwiające wykrywanie farm fotowoltaicznych na podstawie danych teledetekcyjnych

-   dane przestrzenne stworzone przez algorytm(y) na podstawie danych teledetekcyjnych: warstwa z obiektami o geometrii typu polygon lub warstwa rastrowa (powierzchniowa reprezentacja farm fotowoltaicznych) i/lub warstwa z obiektami o geometrii typu point (punktowa reprezentacja występowania farmy fotowoltaicznej w danym miejscu (centroidy obiektów o geometrii typu polygon))

## Dodatkowe źródła informacji

### Dane

-   Program Sentinel-2 <br> [kanały Sentinel-2](https://docs.sentinel-hub.com/api/latest/data/sentinel-2-l2a/#available-bands-and-data) \| [CREODIAS](https://creodias.eu/)
-   Program PlanetScope <br> [kanały PlanetScope](https://developers.planet.com/docs/apis/data/sensors/) \| [Planet](https://www.planet.com/?utm_source=google&utm_medium=paid-search&utm_campaign=discovery-brd&utm_content=homepage)
-   Ortofotomapa GUGiK <br> [Ortofotomapa](https://www.geoportal.gov.pl/dane/ortofotomapa) \| [GUGiK](https://www.gov.pl/web/gugik)

### Literatura

-   praca licencjacka [Detekcja kolektorów i paneli słonecznych na podstawie zdjęć lotniczych miasta Poznania z wykorzystaniem głębokich sieci neuronowych](https://github.com/DepartmentOfStatisticsPUE/prace-dyplomowe/blob/master/licencjat/2019-voss112124lic.pdf) (Voss 2019)
-   praca magisterska [Wykorzystanie głębokich sieci neuronowych na potrzeby statystyki energii odnawialnej](https://github.com/DepartmentOfStatisticsPUE/prace-dyplomowe/blob/master/magisterskie/2021-voss.pdf) (Voss 2021)

</p>
